version: '3'

services:
  web:
    container_name: fyp_forecasting_web
    image: rikkaneko/fyp_forecasting_web
    build: .
    ports: 
      - "8443:18443"
    volumes: 
      - ../data:/etc/nginx/certs
      - ./content:/app
